# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorseForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('breed', models.CharField(blank=True, max_length=128)),
                ('height', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.CharField(blank=True, max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('main_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
